## This notebook converts raw which is present in MS excel sheets to csv files.

In [1]:
import pandas as pd
from os import path

### Loading yearly $CO_{2}$ emmision data from excel files into dataframe

In [2]:
co2_year_data_file_path = path.join("raw_data", "carbon_dioxide_data","CO2_YEARLY_DATA_1970-2021.xlsx")
df_co2_yearly_ipcc_2006 = pd.read_excel(co2_year_data_file_path, sheet_name= 0, usecols="A:BH", skiprows=10)
df_co2_yearly_ipcc_1996 = pd.read_excel(co2_year_data_file_path, sheet_name= 1, usecols="A:BH", skiprows=10)
df_co2_yearly_total = pd.read_excel(co2_year_data_file_path, sheet_name= 2, usecols="A:BE", skiprows=10)

In [3]:
df_co2_yearly_ipcc_2006.head()

,IPCC_annex,C_group_IM24_sh,Country_code_A3,Name,ipcc_code_2006_for_standard_report,ipcc_code_2006_for_standard_report_name,Substance,fossil_bio,Y_1970,Y_1971,...,Y_2012,Y_2013,Y_2014,Y_2015,Y_2016,Y_2017,Y_2018,Y_2019,Y_2020,Y_2021
0,Non-Annex_I,Rest Central America,ABW,Aruba,1.A.1.a,Main Activity Electricity and Heat Production,CO2,bio,0.022397,0.021412,...,1.337603,2.371433,2.497066,2.970795,2.438748,2.509098,3.096665,3.255611,3.378899,3.378899
1,Non-Annex_I,Rest Central America,ABW,Aruba,1.A.2,Manufacturing Industries and Construction,CO2,bio,12.228673,11.690942,...,9.856529,6.886571,6.890052,7.378661,7.853166,9.340506,7.365402,7.718069,8.047569,8.047569
2,Non-Annex_I,Rest Central America,ABW,Aruba,1.A.4,Residential and other sectors,CO2,bio,0.879948,0.845336,...,6.473158,6.021210,6.630579,5.848465,6.489807,6.417006,6.410401,4.571319,7.808080,7.808080
3,Non-Annex_I,Rest Central America,ABW,Aruba,1.A.5,Non-Specified,CO2,bio,0.058367,0.056820,...,1.714841,1.721481,1.838701,2.157164,1.972983,2.068339,2.147736,2.004358,2.450398,2.450398
4,Non-Annex_I,Rest Central America,ABW,Aruba,1.B.1,Solid Fuels,CO2,bio,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df_co2_yearly_ipcc_1996.head()

,IPCC_annex,C_group_IM24_sh,Country_code_A3,Name,ipcc_code_1996_for_standard_report,ipcc_code_1996_for_standard_report_name,Substance,fossil_bio,Y_1970,Y_1971,...,Y_2012,Y_2013,Y_2014,Y_2015,Y_2016,Y_2017,Y_2018,Y_2019,Y_2020,Y_2021
0,Non-Annex_I,Rest Central America,ABW,Aruba,1A1a,Public electricity and heat production,CO2,bio,0.022397,0.021412,...,1.337603,2.371433,2.497066,2.970795,2.438748,2.509098,3.096665,3.255611,3.378899,3.378899
1,Non-Annex_I,Rest Central America,ABW,Aruba,1A2,Manufacturing Industries and Construction,CO2,bio,12.228673,11.690942,...,9.856529,6.886571,6.890052,7.378661,7.853166,9.340506,7.365402,7.718069,8.047569,8.047569
2,Non-Annex_I,Rest Central America,ABW,Aruba,1A4,Residential and other sectors,CO2,bio,0.938315,0.902156,...,8.187999,7.742691,8.469280,8.005629,8.462789,8.485345,8.558136,6.575677,10.258478,10.258478
3,Non-Annex_I,Rest Central America,ABW,Aruba,1B1,Fugitive emissions from solid fuels,CO2,bio,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Non-Annex_I,Rest Central America,ABW,Aruba,1A1a,Public electricity and heat production,CO2,fossil,34.724363,34.724363,...,896.292148,846.442488,867.820889,875.169570,865.655963,636.499816,626.469844,644.431576,531.846511,592.536869

In [5]:
df_co2_yearly_total.head()

,IPCC_annex,C_group_IM24_sh,Country_code_A3,Name,Substance,Y_1970,Y_1971,Y_1972,Y_1973,Y_1974,...,Y_2012,Y_2013,Y_2014,Y_2015,Y_2016,Y_2017,Y_2018,Y_2019,Y_2020,Y_2021
0,Non-Annex_I,Rest Central America,ABW,Aruba,CO2,95.065424,94.503709,105.847814,109.863856,99.977179,...,1637.822831,1605.689731,1633.584420,1626.234050,1597.398255,1335.792882,1366.614574,1404.705123,1166.018409,1295.818804
1,Non-Annex_I,India +,AFG,Afghanistan,CO2,3343.054709,3318.411036,3545.865063,3592.563616,4075.638761,...,14462.288815,12796.268484,12478.108782,12551.087669,11760.799383,12117.693742,12736.811832,12215.717086,12525.011330,12553.576369
2,Non-Annex_I,Southern_Africa,AGO,Angola,CO2,20393.274068,19959.926969,21860.851718,22960.875811,23436.330631,...,45747.276981,51282.174272,53677.191990,56211.792887,55507.493078,51285.300069,49702.305850,51343.735537,49153.126915,50275.123467
3,Non-Annex_I,Rest Central America,AIA,Anguilla,CO2,2.168292,2.168325,2.263753,2.108963,2.350261,...,26.023228,27.940512,27.896061,28.005426,28.339881,29.062445,28.222994,27.579993,22.779488,25.408720
4,Int. Aviation,Int. Aviation,AIR,Int. Aviation,CO2,169300.996554,169300.996554,179147.487130,186892.096441,179793.330898,...,472721.118697,480909.126246,496627.696509,524654.034526,548207.777357,582230.489693,609630.481638,617763.229264,338144.083387,390166.250062

### Saving yearly $CO_{2}$ emmision data in csv files

In [6]:
csv_dir_path = path.join("data","carbon_dioxide")
df_co2_yearly_ipcc_1996.to_csv(path.join(csv_dir_path, "co2_yearly_ipcc_1996.csv"), index= False)
df_co2_yearly_ipcc_2006.to_csv(path.join(csv_dir_path, "co2_yearly_ipcc_2006.csv"),index= False)
df_co2_yearly_total.to_csv(path.join(csv_dir_path, "co2_yearly_ipcc_total.csv"),index= False)

### Loading monthly $CO_{2}$ emmision data from excel file in dataframe

In [7]:
co2_monthly_data_file_path = path.join("raw_data", "carbon_dioxide_data","CO2_Monthly_2000_2021.xlsx")
df_co2_monthly_ipcc_2006 = pd.read_excel(co2_monthly_data_file_path, sheet_name= 0, usecols="A:U", skiprows=9)
df_co2_monthly_ipcc_1996 = pd.read_excel(co2_monthly_data_file_path, sheet_name= 1, usecols="A:U", skiprows=9)
df_co2_monthly_total = pd.read_excel(co2_monthly_data_file_path, sheet_name= 2, usecols="A:R", skiprows=9)

### Saving monthly $CO_{2}$ emmision data in csv files

In [8]:
csv_dir_path = path.join("data","carbon_dioxide")
df_co2_monthly_ipcc_1996.to_csv(path.join(csv_dir_path, "co2_monthly_ipcc_1996.csv"), index= False)
df_co2_monthly_ipcc_2006.to_csv(path.join(csv_dir_path, "co2_monthly_ipcc_2006.csv"),index= False)
df_co2_monthly_total.to_csv(path.join(csv_dir_path, "co2_monthly_ipcc_total.csv"),index= False)